/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'USER' at '16. 8. 24 오후 4:45' with Gradle 3.0
 *
 * @author USER, @date 16. 8. 24 오후 4:45
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
